export const searchForm = document.createElement('form');
searchForm.className = 'search';
document.body.appendChild(searchForm);
export const submitForm = document.createElement('button');
submitForm.setAttribute('type','submit');
submitForm.setAttribute('name','search-btn');
submitForm.setAttribute('id','search-btn');
submitForm.setAttribute('value','');
searchForm.appendChild(submitForm);
export const search = document.createElement('input');
search.setAttribute('id', 'stringSearch');
search.setAttribute('type', 'search');
search.setAttribute('placeholder', 'Search');
searchForm.appendChild(search);
export const wrapper = document.createElement('div');
wrapper.setAttribute('id', 'wrapper');
export const resultDiv = document.createElement('div');
resultDiv.setAttribute('id', 'result');
wrapper.appendChild(resultDiv);
export const pages = document.createElement('div');
pages.setAttribute('id', 'pages');
